### ISSUE TITLE
Adding Channel Module

### ISSUE THREAD

**Issue by MouadxBth** [MouadxBth/ft_transcendence#3]
Creating the Channel Module, responsible for the CRUD operations on Channels

**Comment by brkncookie** [comment]
added an initial Channel module to handle CRUD operations.

**Comment by brkncookie** [comment]
still need route protection, ownership authenticity, ownership transfer (to be discussed) and for sure the necessary tests.

**Comment by MouadxBth** [comment]
Still need Swagger Documentation too.

**Comment by brkncookie** [comment]
will do.

**Comment by brkncookie** [comment]
finished writing tests.

**Comment by brkncookie** [comment]
ready for review

**Comment by MouadxBth** [comment]
remaining aspects are:
- Adding and configuring websockets for sending messages in channels, each message sent by a given member should be broadcasted to all the members of that channel, of course, only authenticated channel members are allowed to send messages through the websockets, each message sent through the socket should be saved to the database
- Adding role based channel management, where channel members can neither ban n'or mute another member of a channel, unless if he was an admin or a channel owner, channel admins can't ban n'or mute other channel admins, only a channel owner can
- Should handle the case of whether a channel owner leaves his channel, whether it should be deleted or not (in my opinion it should be deleted)
- Adding channel invites, as well as maybe generating a custom channel invite link, where a channel admin/owner can invite another member using a channel invite link, should also think about who can generate this channel invite link, (in my opinion, for regular and protected channels, members can generate these links, for private channels, only admins and above can do so)
- Adding the read status functionality to indicate whether the last sent messages are read by the recipient of the message or not
- Adding the ability to modify/delete messages as well as differentiate between regular and modified messages
- Fetching a channel should be dynamic (pagination) to allow for performant message history, considering 25 messages per request as a limit
